# Generated by Django 5.1 on 2024-08-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compliment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_to', models.BigIntegerField()),
                ('text', models.TextField()),
                ('compliment_type', models.CharField(choices=[('simple', 'Обычный'), ('special', 'Специальный'), ('extra_special', 'Интимный')], default='simple', max_length=15)),
            ],
        ),
    ]
